# Generated by Django 5.2.7 on 2025-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
