# Generated by Django 5.2.7 on 2025-10-30 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(message='Only alphanumeric characters, number, -_ are allowed.', regex='^[a-zA-Z0-9_-]+$')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
