# Generated by Django 5.2.7 on 2025-11-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('order_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_username', models.CharField(max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='cents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('master_order_number', models.BigIntegerField()),
                ('order_number', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('sub_order_number', models.CharField(max_length=23)),
                ('product_id', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.PositiveIntegerField(default=0, help_text='cents')),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='cents')),
                ('status', models.CharField(default='placed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('master_order_number', models.BigIntegerField()),
                ('sub_order_number', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('seller_username', models.CharField(max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='cents')),
            ],
        ),
    ]
