# Generated by Django 5.2.7 on 2025-10-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('seller_id', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product_id', models.UUIDField()),
            ],
        ),
    ]
